//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataManagementWordPressDB.DataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WordPressEntities : DbContext
    {
        public WordPressEntities()
            : base("name=WordPressEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<wp_commentmeta> wp_commentmeta { get; set; }
        public DbSet<wp_comments> wp_comments { get; set; }
        public DbSet<wp_lead_form> wp_lead_form { get; set; }
        public DbSet<wp_lead_form_data> wp_lead_form_data { get; set; }
        public DbSet<wp_lead_form_extension> wp_lead_form_extension { get; set; }
        public DbSet<wp_lead_form_options> wp_lead_form_options { get; set; }
        public DbSet<wp_links> wp_links { get; set; }
        public DbSet<wp_options> wp_options { get; set; }
        public DbSet<wp_postmeta> wp_postmeta { get; set; }
        public DbSet<wp_posts> wp_posts { get; set; }
        public DbSet<wp_term_relationships> wp_term_relationships { get; set; }
        public DbSet<wp_term_taxonomy> wp_term_taxonomy { get; set; }
        public DbSet<wp_termmeta> wp_termmeta { get; set; }
        public DbSet<wp_terms> wp_terms { get; set; }
        public DbSet<wp_th_popup> wp_th_popup { get; set; }
        public DbSet<wp_usermeta> wp_usermeta { get; set; }
        public DbSet<wp_users> wp_users { get; set; }
        public DbSet<wp_wc_download_log> wp_wc_download_log { get; set; }
        public DbSet<wp_wc_webhooks> wp_wc_webhooks { get; set; }
        public DbSet<wp_wcpdf_invoice_number> wp_wcpdf_invoice_number { get; set; }
        public DbSet<wp_woocommerce_api_keys> wp_woocommerce_api_keys { get; set; }
        public DbSet<wp_woocommerce_attribute_taxonomies> wp_woocommerce_attribute_taxonomies { get; set; }
        public DbSet<wp_woocommerce_downloadable_product_permissions> wp_woocommerce_downloadable_product_permissions { get; set; }
        public DbSet<wp_woocommerce_log> wp_woocommerce_log { get; set; }
        public DbSet<wp_woocommerce_order_itemmeta> wp_woocommerce_order_itemmeta { get; set; }
        public DbSet<wp_woocommerce_order_items> wp_woocommerce_order_items { get; set; }
        public DbSet<wp_woocommerce_payment_tokenmeta> wp_woocommerce_payment_tokenmeta { get; set; }
        public DbSet<wp_woocommerce_payment_tokens> wp_woocommerce_payment_tokens { get; set; }
        public DbSet<wp_woocommerce_sessions> wp_woocommerce_sessions { get; set; }
        public DbSet<wp_woocommerce_shipping_zone_locations> wp_woocommerce_shipping_zone_locations { get; set; }
        public DbSet<wp_woocommerce_shipping_zone_methods> wp_woocommerce_shipping_zone_methods { get; set; }
        public DbSet<wp_woocommerce_shipping_zones> wp_woocommerce_shipping_zones { get; set; }
        public DbSet<wp_woocommerce_tax_rate_locations> wp_woocommerce_tax_rate_locations { get; set; }
        public DbSet<wp_woocommerce_tax_rates> wp_woocommerce_tax_rates { get; set; }
    }
}
