//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataManagementWordPressDB.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class wp_lead_form_extension
    {
        public int eid { get; set; }
        public int form_id { get; set; }
        public string ext_api { get; set; }
        public string ext_map { get; set; }
        public sbyte active { get; set; }
        public int ext_type { get; set; }
        public System.DateTime edate { get; set; }
    }
}
