//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataManagementWordPressDB.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class wp_th_popup
    {
        public int ID { get; set; }
        public string popupData { get; set; }
        public string settings { get; set; }
        public System.DateTime popupDate { get; set; }
    }
}
