//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataManagementWordPressDB.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class wp_woocommerce_downloadable_product_permissions
    {
        public wp_woocommerce_downloadable_product_permissions()
        {
            this.wp_wc_download_log = new HashSet<wp_wc_download_log>();
        }
    
        public decimal permission_id { get; set; }
        public string download_id { get; set; }
        public decimal product_id { get; set; }
        public decimal order_id { get; set; }
        public string order_key { get; set; }
        public string user_email { get; set; }
        public Nullable<decimal> user_id { get; set; }
        public string downloads_remaining { get; set; }
        public System.DateTime access_granted { get; set; }
        public Nullable<System.DateTime> access_expires { get; set; }
        public decimal download_count { get; set; }
    
        public virtual ICollection<wp_wc_download_log> wp_wc_download_log { get; set; }
    }
}
