//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPDataRepo
{
    using System;
    using System.Collections.Generic;
    
    public partial class wp_lead_form
    {
        public int id { get; set; }
        public string form_title { get; set; }
        public string form_data { get; set; }
        public System.DateTime date { get; set; }
        public string mail_setting { get; set; }
        public string usermail_setting { get; set; }
        public string multiData { get; set; }
        public string form_skin { get; set; }
        public string form_status { get; set; }
        public string captcha_status { get; set; }
        public string storeType { get; set; }
    }
}
