//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPDataRepo
{
    using System;
    using System.Collections.Generic;
    
    public partial class wp_lead_form_options
    {
        public int fid { get; set; }
        public string colorData { get; set; }
    }
}
