//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPDataRepo
{
    using System;
    using System.Collections.Generic;
    
    public partial class wp_lead_form_data
    {
        public int id { get; set; }
        public Nullable<int> form_id { get; set; }
        public string form_data { get; set; }
        public string ip_address { get; set; }
        public string server_request { get; set; }
        public Nullable<System.DateTime> date { get; set; }
    }
}
